### ISSUE TITLE
[request] v30.3.1

### ISSUE THREAD

**Issue by daiyam** [riscv-forks/electron-riscv-releases#2]
Hi @kxxt,

Can you generate the `v30.3.1` since it's needed to the next Insiders version of VSCodium? Thx

https://github.com/VSCodium/vscodium/actions/runs/10354812354/job/28661776958#step:8:54

**Comment by kxxt** [comment]
> Can you generate the v30.3.1 since it's needed to the next Insiders version of VSCodium? Thx

Sure. I think I forgot v30.3.1.

**Comment by kxxt** [comment]
It is building now: https://github.com/riscv-forks/electron-riscv-releases/actions/runs/10355223817/job/28662354164

v30.3.1.riscv1 should be available after several hours

I updated the source branch but forgot to actually build it. Sorry for the delay.

**Comment by daiyam** [comment]
Thx for your prompt answer.

> Sorry for the delay.

No worry. This month, I'm very late for VSCodium...

**Comment by kxxt** [comment]
It's available now: https://github.com/riscv-forks/electron-riscv-releases/releases/tag/v30.3.1.riscv1
