### ISSUE TITLE
version file doesn't match in electron-vXX.X.X-linux-riscv64.zip

### ISSUE THREAD

**Issue by bitsk** [riscv-forks/electron-riscv-releases#4]

**Comment by kxxt** [comment]
Could you share a link to the zip file that has this problem?

**Comment by kxxt** [comment]
> Could you share a link to the zip file that has this problem?

No need. I see that electron 31 and 32 are affected. Perhaps electron upstream changed the way to determine the electron version.

**Comment by kxxt** [comment]
Thanks for the report. It's because some upstream tags are not available in CI when building. It has been fixed by https://github.com/riscv-forks/electron-riscv-releases/commit/8989a0567bbf1e3491e08a6996c100f8a494ae34.

Fixed in v32.0.1.riscv2 and v31.4.0.riscv2  which will be available shortly.

**Comment by bitsk** [comment]
Thanks for the quick fix,  v30.3.1 still has this issue

**Comment by kxxt** [comment]
> Thanks for the quick fix, v30.3.1 still has this issue

Fixed in v30.3.1.riscv2
