### ISSUE TITLE
v32.2.5

### ISSUE THREAD

**Issue by daiyam** [riscv-forks/electron-riscv-releases#5]
Hi @kxxt,

Can you build the `v32.2.5` which has been release just a few hours ago?
It's fixing the File menu bug. (https://github.com/VSCodium/vscodium/issues/2082)

**Comment by kxxt** [comment]
Hi @daiyam, thanks for reaching out. It is being built now: https://github.com/riscv-forks/electron-riscv-releases/actions/runs/11866605331/job/33073556283

**Comment by kxxt** [comment]
It is available now: https://github.com/riscv-forks/electron-riscv-releases/releases/tag/v32.2.5.riscv1

Sorry for the delay.
